#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-disruptor_thrift_server
Version  : 0.3.7
Release  : 1
URL      : https://github.com/xedin/disruptor_thrift_server/archive/0.3.7.tar.gz
Source0  : https://github.com/xedin/disruptor_thrift_server/archive/0.3.7.tar.gz
Source1  : http://repo1.maven.org/maven2/com/thinkaurelius/thrift/thrift-server/0.3.7/thrift-server-0.3.7.jar
Source2  : http://repo1.maven.org/maven2/com/thinkaurelius/thrift/thrift-server/0.3.7/thrift-server-0.3.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-disruptor_thrift_server-data = %{version}-%{release}
Requires: mvn-disruptor_thrift_server-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
## LMAX Disruptor backed Thrift Server implementation.
This server is half-sync/half-async and uses separate invocation executor.

%package data
Summary: data components for the mvn-disruptor_thrift_server package.
Group: Data

%description data
data components for the mvn-disruptor_thrift_server package.


%package license
Summary: license components for the mvn-disruptor_thrift_server package.
Group: Default

%description license
license components for the mvn-disruptor_thrift_server package.


%prep
%setup -q -n disruptor_thrift_server-0.3.7

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-disruptor_thrift_server
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-disruptor_thrift_server/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thinkaurelius/thrift/thrift-server/0.3.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/thinkaurelius/thrift/thrift-server/0.3.7/thrift-server-0.3.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thinkaurelius/thrift/thrift-server/0.3.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/thinkaurelius/thrift/thrift-server/0.3.7/thrift-server-0.3.7.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/thinkaurelius/thrift/thrift-server/0.3.7/thrift-server-0.3.7.jar
/usr/share/java/.m2/repository/com/thinkaurelius/thrift/thrift-server/0.3.7/thrift-server-0.3.7.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-disruptor_thrift_server/LICENSE.txt
